FROM nginx:alpine

# Copier la configuration nginx
COPY nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

# Copier le code de l'application
COPY www/ /var/www/html/

# Définir les permissions
RUN chown -R nginx:nginx /var/www/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
